#placeholder yaml file for now
spring:
  datasource:
    #temp url until db is fully setup
    url: jdbc:mysql://localhost:3306/testdb
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: backend